### ISSUE TITLE
[Error] Network error  "Connection to the host has been lost"

### ISSUE THREAD

**Issue by marcantoinethimm** [feydan/satisfactory-tools#7]
Hi, I installed successfully the server following the instruction but I'm getting every time a network error when trying to join the server. 
I checked the log and everything seems just fine, the auto-shutdown also works fine and the API is returning that the server is running.

When I try to create the map and start playing it creates the map but doesn't let me connect to the server : 

Status of the server, the game seems to be created : 

![image](https://user-images.githubusercontent.com/47699758/152870823-98870c2d-c529-44a1-b06c-f62a432daa46.png)

When trying to connect :

![image](https://user-images.githubusercontent.com/47699758/152870718-8a994b68-2703-4fb9-bbd5-0c36f5b48af6.png)

Tell me if you need a particular log.

Thanks in advance

**Comment by feydan** [comment]
I haven't seen this before when using the server.  You could try inspecting the Satisfactory logs when you connect to see if there are errors.

`journalctl -u satisfactory.service --since today -f`

**Comment by marcantoinethimm** [comment]
Hi just find out what happened, I was having some mods activated and it seems that the server was blocking my connection because of these mods #

**Comment by feydan** [comment]
Thanks for the update!
